[package]
name = "mtop"
version = "0.1.0"
edition = "2021"

[dependencies]
psutil = "3.3.0"
tui = { version = "0.19"}
crossterm = "0.26"
sysinfo = "0.25"
regex = "1.7"
lazy_static = "1.4"
crossbeam-channel = "0.5"
libc = "0.2"
